# Generated by Django 2.1.2 on 2018-10-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='userzy',
            field=models.ManyToManyField(to='main.User'),
        ),
    ]
