# Generated by Django 2.1.2 on 2018-10-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181005_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grupy',
            field=models.ManyToManyField(related_name='users', to='main.Group'),
        ),
    ]
