# Generated by Django 2.1.2 on 2018-10-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181007_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grupy',
            field=models.ManyToManyField(related_name='user_set', to='main.Group'),
        ),
    ]
