# Generated by Django 2.1.2 on 2018-10-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181008_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='grupy',
        ),
        migrations.AddField(
            model_name='group',
            name='grupy',
            field=models.ManyToManyField(related_name='group_set', to='main.User'),
        ),
    ]
