# Generated by Django 2.1.2 on 2018-10-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181008_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grupy',
            field=models.ManyToManyField(blank=True, null=True, related_name='group_set', to='main.User'),
        ),
    ]
